In [1]:
import tensorflow as tf

In [14]:
a = [[4,4,4,4],
     [4,4,4,4],
     [4,4,4,4],
     [4,4,4,4]]
b = [[5,5,5,5],
     [5,5,5,5],
     [5,5,5,5],
     [5,5,5,5]]

# a = [4]
# b = [5]

In [15]:
a = tf.cast(a,tf.float32)
b = tf.cast(b,tf.float32)

In [16]:
cost = tf.losses.mean_squared_error(a,b)
print(cost)

Tensor("mean_squared_error_2/value:0", shape=(), dtype=float32)


In [17]:
sess = tf.Session()
print(sess.run(cost))

1.0


In [18]:
cost2 = tf.abs(a-b)
print(sess.run(cost2))
print(sess.run(tf.reduce_sum(cost2)))
print(sess.run(tf.reduce_mean(cost2)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
16.0
1.0
